### ISSUE TITLE
Add me to the team plz

### ISSUE THREAD

**Issue by andrewlalis** [tomdenboon/ChatFacts#1]
I think by letting me supply you with a top-notch relational database and webserver system, your chat facts will be more powerful than you could ever imagine.

**Comment by GeorgeArgyrousis** [comment]
Don't tell me that you are going to use Twillio....

**Comment by andrewlalis** [comment]
No, I was gonna go for Spring + Hibernate. I don't even know what twilio is, but I'll use it somehow.
